//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApps.Samples
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public System.DateTime Year { get; set; }
        public string Colour { get; set; }
        public string CarName { get; set; }
        public string Manufracturer { get; set; }
        public decimal Price { get; set; }
    }
}
